# Generated by Django 6.0.6 on 2026-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departureevent',
            name='type',
            field=models.CharField(choices=[('resignation', 'По собственному желанию'), ('maternity', 'Декрет / отпуск по уходу'), ('retirement', 'Выход на пенсию'), ('dismissal_violation', 'Увольнение за нарушения'), ('dismissal_cert', 'Увольнение по аттестации'), ('other', 'Другое')], max_length=50),
        ),
    ]
